# Generated by Django 3.2.6 on 2021-09-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=30)),
                ('contact_no', models.CharField(max_length=12)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=30)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('total_payment', models.IntegerField()),
            ],
        ),
    ]
