# Generated by Django 3.2.6 on 2021-09-17 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_model',
            name='check_out',
        ),
        migrations.RemoveField(
            model_name='customer_model',
            name='total_payment',
        ),
    ]
